[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Omit benign public identifiers from secrets scanning (prevents false positives)
  SECRETS_SCAN_OMIT_KEYS = "AUTH0_AUDIENCE,AUTH0_CLIENT_ID,AUTH0_DOMAIN,AUTH0_ISSUER_BASE_URL,SUPABASE_ANON_KEY"
  # Ignore generated public outputs where those identifiers necessarily appear
  SECRETS_SCAN_OMIT_PATHS = "public/sitemap*.xml,public/robots.txt,dist/**"

# Disable Netlify Visual Editor to prevent Studio Preview Error
[context.production.environment]
  DISABLE_NETLIFY_VISUAL_EDITOR = "true"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Admin redirect for Netlify CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

